package:
  name: r-llmcelltype
  version: 0.0.2

source:
  path: ..

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-ellmer

  run:
    - r-base
    - r-ellmer

test:
  commands:
    - $R -e "library('LLMCellType')"

about:
  home: https://github.com/pwwang/LLMCellType
  license: MIT
  summary: llmcelltype is an R package for cell type annotation using large language models.
  license_family: MIT
  license_file: LICENSE.md
