#' Cell type annotation with large language models
#'
#' Annotate cell types by LLM chat models in a Seurat pipeline or with a custom
#' gene list. Supported providers: OpenAI, Anthropic, Google Gemini, and local
#' Ollama servers (via the ellmer package).
#'
#' If used in a Seurat pipeline, Seurat FindAllMarkers() function needs to be
#' run first and the differential gene table generated by Seurat will serve as
#' the input. If the input is a custom list of genes, one cell type is
#' identified for each element in the list.
#'
#' Note: set the API key of your provider as an environment variable
#' (\code{OPENAI_API_KEY}, \code{ANTHROPIC_API_KEY}, \code{GOOGLE_API_KEY} or
#' \code{GEMINI_API_KEY}) or pass it via the \code{api_key} argument. If no key
#' is available, the prompt itself is returned, which can be pasted into the
#' chat UI of your provider. No API key is required for provider = "ollama".
#'
#' @param input Either the differential gene table returned by Seurat
#'   FindAllMarkers() function, or a list of genes.
#' @param tissuename Optional input of tissue name.
#' @param provider One of "openai" (default), "anthropic", "gemini" or
#'   "ollama". "ollama" runs against a local Ollama server and does not require
#'   an API key.
#' @param model Model identifier accepted by the provider. If NULL (default),
#'   the provider's default model is used. provider = "ollama" always requires
#'   an explicit model, e.g. "llama3.1".
#' @param base_url Optional API base URL override, e.g. for OpenAI-compatible
#'   endpoints (such as OpenRouter, DeepSeek or local servers).
#' @param api_key Optional API key. Defaults to the provider's standard
#'   environment variable.
#' @param topgenenumber Number of top differential genes to be used if input is
#'   Seurat differential genes.
#' @param return_prompt Logical, return the prompt instead of the cell type annotations.
#'   This is useful for debugging or when you want to see the prompt sent to the LLM.
#'   When the API key is needed but not available, the prompt is always returned regardless of this argument.
#' @export
#' @return A named vector of cell types when an API key is available, or the
#'   prompt itself when no API key is set.
#' @examples
#' # No API key set: the prompt itself is returned
#' Sys.setenv(OPENAI_API_KEY = '')
#' llmcelltype(list(gs1 = c('CD4', 'CD3D'), gs2 = 'CD14'), tissuename = NULL)
llmcelltype <- function(
  input,
  tissuename = NULL,
  provider = c("openai", "anthropic", "gemini", "ollama"),
  model = NULL,
  base_url = NULL,
  api_key = NULL,
  topgenenumber = 10,
  return_prompt = FALSE
) {
  provider <- match.arg(provider)

  if (is.list(input) && !is.data.frame(input)) {
    input <- sapply(input, paste, collapse = ',')
  } else {
    input <- input[input$avg_log2FC > 0, , drop = FALSE]
    input <- input[order(input$cluster, -input$avg_log2FC), , drop = FALSE]
    input <- tapply(input$gene, list(input$cluster), function(i) {
      paste0(i[1:topgenenumber], collapse = ',')
    })
  }

  if ((.llm_needs_key(provider) && !.llm_has_key(provider, api_key)) || return_prompt) {
    print(paste0(
      "Note: ",
      .llm_provider_label(provider),
      " API key not found, or return_prompt is TRUE: returning the prompt itself."
    ))
    return(.llm_prompt_no_key(tissuename, input))
  }

  if (.llm_needs_key(provider)) {
    print(paste0(
      "Note: ",
      .llm_provider_label(provider),
      " API key found: returning the cell type annotations."
    ))
  }
  chat <- .llm_chat(provider, model, base_url, api_key)

  # one call per ~200 clusters: input per cluster is a few tokens, and output
  # per chunk is a few hundred short lines, well within today's output caps.
  # The retry loop below re-sends a whole chunk, so a chunk must stay small
  # enough that a bad answer is cheap to retry.
  cutnum <- ceiling(length(input) / 200)
  if (cutnum > 1) {
    cid <- as.numeric(cut(1:length(input), cutnum))
  } else {
    cid <- rep(1, length(input))
  }

  allres <- sapply(
    seq_len(cutnum),
    function(i) {
      id <- which(cid == i)
      n <- length(id)
      res <- character()
      # a model that gets the line count wrong once is likely to repeat it;
      # cap attempts and tell it what went wrong instead of looping forever
      for (attempt in seq_len(3)) {
        hint <- if (attempt > 1) {
          paste0(
            'Your previous answer had ', length(res), ' lines, but exactly ',
            n, ' were required (one per row). Reply again with ', n,
            ' plain cell type names, one per line, nothing else.'
          )
        } else {
          NULL
        }
        k <- chat$chat(.llm_prompt_chunk(tissuename, input[id], hint))
        res <- strsplit(k, '\n')[[1]]
        res <- res[nzchar(trimws(res))]
        if (length(res) == n) break
      }
      if (length(res) != n) {
        stop(
          'Could not parse the LLM answer for chunk ', i,
          ': expected ', n, ' cell types, got ', length(res)
        )
      }
      names(res) <- names(input)[id]
      res
    },
    simplify = FALSE
  )

  print(
    'Note: It is always recommended to check the results returned by the model in case of\n AI hallucination, before going to down-stream analysis.'
  )
  gsub(',$', '', unlist(allres))
}

#' @rdname llmcelltype
#' @export
gptcelltype <- function(
  input,
  tissuename = NULL,
  model = 'gpt-4',
  topgenenumber = 10
) {
  llmcelltype(
    input,
    tissuename,
    provider = "openai",
    model = model,
    topgenenumber = topgenenumber
  )
}

.llm_provider_label <- function(provider) {
  switch(
    provider,
    openai = "OpenAI",
    anthropic = "Anthropic",
    gemini = "Google Gemini",
    ollama = "Ollama"
  )
}

# providers that read an API key from the environment
.llm_needs_key <- function(provider) {
  provider != "ollama"
}

.llm_has_key <- function(provider, api_key) {
  if (!is.null(api_key)) {
    return(TRUE)
  }
  switch(
    provider,
    openai = nzchar(Sys.getenv("OPENAI_API_KEY")),
    anthropic = nzchar(Sys.getenv("ANTHROPIC_API_KEY")),
    gemini = nzchar(Sys.getenv("GOOGLE_API_KEY")) ||
      nzchar(Sys.getenv("GEMINI_API_KEY")),
    ollama = TRUE
  )
}

# chat object for a provider; NULL model -> provider default (ellmer), but
# ollama requires an explicit model
.llm_chat <- function(provider, model = NULL, base_url = NULL, api_key = NULL) {
  if (provider == "ollama" && is.null(model)) {
    stop('provider = "ollama" requires a model, e.g. model = "llama3.1"')
  }
  fn <- switch(
    provider,
    openai = ellmer::chat_openai,
    anthropic = ellmer::chat_anthropic,
    gemini = ellmer::chat_google_gemini,
    ollama = ellmer::chat_ollama
  )
  args <- list()
  if (!is.null(model)) {
    args$model <- model
  }
  if (!is.null(base_url)) {
    args$base_url <- base_url
  }
  if (!is.null(api_key)) {
    args$credentials <- function() api_key
  }
  do.call(fn, args)
}

# prompt returned when no API key is available
.llm_prompt_no_key <- function(tissuename, input) {
  paste0(
    'Identify cell types of ',
    tissuename,
    ' cells using the following markers separately for each\n row. Only provide the cell type name. Do not show numbers before the name.\n Some can be a mixture of multiple cell types. ',
    "\n",
    paste0(names(input), ':', unlist(input), collapse = "\n")
  )
}

# prompt sent to the model for one chunk of clusters; states an explicit
# output contract (exactly N lines, in order) because without it models add
# preambles or wrap lines, which fails the parse check and forces retries;
# hint carries the format feedback shown to the model on a retry
.llm_prompt_chunk <- function(tissuename, genes, hint = NULL) {
  prompt <- paste0(
    'Identify cell types of ', tissuename,
    ' cells using the following markers, one row per cell type:\n',
    paste(genes, collapse = '\n'),
    '\nReply with exactly ', length(genes), ' lines, one line per row above',
    ' and in the same order. Mixtures of cell types are allowed. Plain names',
    ' only - no numbering, no bullets, no preamble, no explanations, no',
    ' blank lines, no code fences.'
  )
  if (!is.null(hint)) {
    prompt <- paste0(prompt, '\n\n', hint)
  }
  prompt
}
